service: auth-api

provider: ${file(../../serverless.base.yml):provider}
plugins: ${file(../../serverless.base.yml):plugins}

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 4000
    reloadHandler: ${file(../../serverless.base.yml):custom.serverless-offline.reloadHandler}
  bundle: ${file(../../serverless.base.yml):custom.bundle}
  esbuild: ${file(../../serverless.base.yml):custom.esbuild}

functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
